=== thoTsou/XML-Projects/files/car_rental_new.xsd
<?xml version ="1.0" encoding ="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="cars">
		<xs:complexType >
			<xs:sequence>
				<xs:element name="car" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>	
					<xs:sequence>
					
						<xs:element name="manufacturer_brand" >
							<xs:complexType mixed="true">
								<xs:sequence>
								<xs:element name="model" type="xs:string" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						
						<xs:element name="extra_car_info" >
							<xs:complexType >
								<xs:attribute name="color" type="xs:string" use="required" />
								<xs:attribute name="mini_model_description" type="xs:string" />
							</xs:complexType>
						</xs:element>
						
						<xs:element name="main_characteristics" >
							<xs:complexType >
							<xs:all>
								<xs:element name="Engine" type="xs:string" />
								<xs:element name="CO2_emissions" >
									<xs:complexType mixed="true" >
										<xs:attribute name="em_unit" type="xs:string" fixed="grCO2/km" use="required" />
										<xs:attribute name="mixed_cycle" >
										<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="yes" />
													<xs:enumeration value="no" />
												</xs:restriction>
											</xs:simpleType>
										</xs:attribute>
									</xs:complexType>
								</xs:element>
								<xs:element name="Fuel_consumption" >
									<xs:complexType mixed="true">
										<xs:attribute name="unit_fuel" type="xs:string" use="required" fixed="lt/100km"/>
										<xs:attribute name="mixed_cycle" >
										<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="yes" />
													<xs:enumeration value="no" />
												</xs:restriction>
											</xs:simpleType>
										</xs:attribute>
									</xs:complexType>
								</xs:element>
							</xs:all>
							</xs:complexType>
						</xs:element>
				
						<xs:element name="economic_info_leasing">
							<xs:complexType >
							<xs:sequence>
								<xs:element name="monthly_leasing" minOccurs="1" maxOccurs="2">
									<xs:complexType mixed="true">
										<xs:attribute name="without_tax" use="required">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="true" />
													<xs:enumeration value="false" />
												</xs:restriction>
											</xs:simpleType>
										</xs:attribute>
										<xs:attribute name="tax" type="xs:string" default="24%"/>
										<xs:attribute name="leasing_unit" type="xs:string" default="euro" use="optional"/>
									</xs:complexType>
								</xs:element>
									
									<xs:element name="payment_in_advance">
										<xs:complexType >
											<xs:sequence>
												<xs:element name="amount" minOccurs="2" maxOccurs="2">
													<xs:complexType mixed="true">
														<xs:attribute name="without_tax" use="required">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="true" />
																	<xs:enumeration value="false" />
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
														<xs:attribute name="tax" type="xs:string" default="24%"/>
														<xs:attribute name="payment_unit" type="xs:string" default="euro" use="optional"/>
													</xs:complexType>
												</xs:element>
												<xs:element name="descr" type="xs:string" minOccurs="0" maxOccurs="1" />
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									
									<xs:element name="retail_price" >
										<xs:complexType mixed="true">
											<xs:attribute name="retail_unit" type="xs:string" default="euro" use="optional" />
										</xs:complexType>
									</xs:element>
									
									<xs:element name="Retail_price_before_taxes" >
										<xs:complexType mixed="true">
											<xs:attribute name="retail_bef_tax_unit" type="xs:string" default="euro" use="optional" />
										</xs:complexType>
									</xs:element>
									
									<xs:element name="detail_econ_info" type="xs:string" />
								
							</xs:sequence>	
							</xs:complexType>
						</xs:element>
						
						<xs:element name="equipment">
							<xs:complexType >
							<xs:sequence>
								<xs:element name="basic_equipment">
									<xs:complexType >
										<xs:sequence>
										<xs:element name="equip" maxOccurs="unbounded">
											<xs:complexType mixed="true">
												<xs:attribute name="id" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="executive_equip" minOccurs="0">
									<xs:complexType >
									<xs:sequence>
										<xs:element name="exec_equip" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType mixed="true">
												<xs:attribute name="id" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							</xs:complexType>
						</xs:element>
						
						<xs:element name="offer_include">
							<xs:complexType >
								<xs:sequence>
									<xs:element name="include" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					
						
					</xs:sequence>
					<xs:attribute name="no" type="xs:string" use="required"/>
					</xs:complexType>
					
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	
</xs:schema>

=== thoTsou/XML-Projects/files/car_rental_new.xml
<?xml version ="1.0" encoding ="UTF-8" ?>



<cars xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="car_rental_new.xsd">
	
	<car no="No.1">
		
		<manufacturer_brand> Renault 
			<model>CLIO V</model>
		</manufacturer_brand>
		
		<extra_car_info color="Λευκό" mini_model_description="1.5 dci 85hp AUTHENTIC MANUAL" />
			

        <main_characteristics>
			<Engine> 1.5 dci 85hp </Engine>
			<CO2_emissions em_unit="grCO2/km">101</CO2_emissions>
            <Fuel_consumption unit_fuel="lt/100km" >3,6 - 3,8</Fuel_consumption>
		</main_characteristics>
		
		<economic_info_leasing>
			<monthly_leasing leasing_unit="euro" without_tax="true">143</monthly_leasing>
			<monthly_leasing leasing_unit="euro" without_tax="false" tax="24_percent">177</monthly_leasing>
			<payment_in_advance>
				<amount payment_unit="euro" without_tax="false" tax="24_percent">3.968</amount>
				<amount payment_unit="euro" without_tax="true">3.200</amount>
				<descr>Λαμβάνεται ως πρώτο μίσθωμα</descr>	
			</payment_in_advance>
			<retail_price retail_unit="euro">15.592</retail_price>
			<Retail_price_before_taxes retail_bef_tax_unit="euro">11.921</Retail_price_before_taxes>
			<detail_econ_info>Η τιμή ισχύει για μίσθωση 48 μηνών και καλύπτει 20.000 χλμ. τον χρόνο.</detail_econ_info>
		</economic_info_leasing>
		
		<equipment>
			<basic_equipment>
				<equip id="e1">(1)ABS με EBV και AFU </equip>
				<equip id="e2">(2)Ηλεκτρονικός έλεγχος ευστάθειας (ESC) και ASR</equip>
				<equip id="e3">(3)Hill Start Assist (σύστημα υποβοήθησης εκκίνησης σε οδόστρωμα με κλίση)</equip>
				<equip id="e4">(4)Μετωπικοί αερόσακοι οδηγού-συνοδηγού</equip>
				<equip id="e5">(5)Αερόσακοι πλευρικοί εμπρός  για την προστασία του κεφαλιού και του θώρακα</equip>
				<equip id="e6">(6)Αερόσακοι τύπου κουρτίνας εμπρός/πίσω </equip>
				<equip id="e7"> (7)Αυτόματο σύστημα πέδησης έκτακτης ανάγκης με ανίχνευση πεζών και δικύκλων (AEB)</equip>
				<equip id="e8">(8)Cruise Control με Speed limiter και χειριστήρια στο τιμόνι</equip>
				<equip id="e9">(9) Αναγνώριση πινακίδων οδικής κυκλοφορίας (TSR) </equip>
				<equip id="e10">(10) Σύστημα υποβοήθησης διατήρησης λωρίδας (LKA) %amp; Προειδοποίηση Αλλαγής Λωρίδας Κυκλοφορίας (LDW)</equip>
				<equip id="e11">(11) Πίνακας οργάνων με εγχρωμη οθόνη 4,2”</equip>
				<equip id="e12">(12) Air Condition με φίλτρο γύρης και μικροσωματιδίων</equip>
				<equip id="e13">(13) Τιμόνι ρυθμιζόμενο σε ύψος και μήκος , με ηλεκτρική υποβοήθηση</equip>
				<equip id="e14">(14) Κάθισμα οδηγού ρυθμιζόμενο σε ύψος</equip>
				<equip id="e15">(15) Εμπρός προσκέφαλα ρυθμιζόμενα καθ'ύψος </equip>
				<equip id="e16">(16) 3 προσκέφαλα πίσω, ρυθμιζόμενα σε ύψος</equip>
				<equip id="e17">(17) Διαιρούμενο πίσω κάθισμα 1/3-2/3</equip>
				<equip id="e18">(18) Ηλεκτρικά παράθυρα εμπρός %amp; Παράθυρο οδηγού συνεχούς λειτουργίας</equip>
				<equip id="e19">(19) Υπολογιστής ταξιδίου</equip>
				<equip id="e20">(20) Διακόπτης ECO</equip>
				<equip id="e21">(21) Ηλεκτρικά ρυθμιζόμενοι %amp; θερμαινόμενοι καθρέφτες</equip>
				<equip id="e22">(22) Κεντρικό κλείδωμα με τηλεχειρισμό (Foldable key )</equip>
				<equip id="e23">(23) Φώτα ημέρας LED</equip>
				<equip id="e24">(24) Τροχοί 15'' IREMIA</equip>
			</basic_equipment>
		</equipment>
		
		<offer_include>
			<include>Συντήρηση και επισκευή αυτοκινήτου</include>
			<include>Πλήρη ασφαλιστική κάλυψη (ίδιες ζημιές με απαλλαγή - 24ωρη οδική βοήθεια)</include>
			<include>Τέλη κυκλοφορίας</include>
			<include>Αντικατάσταση αυτοκινήτου</include>
			<include>Δυνατότητα χρήσης προσωρινού αυτοκινήτου</include>
			<include>Αλλαγή Ελαστικών</include>
		</offer_include>



	</car>
	
	<car no="No.2">
		
		<manufacturer_brand>Mini Cooper 
			<model>Mini Countryman</model>
		</manufacturer_brand>
		
		<extra_car_info color="Μαύρο" mini_model_description="Executive AYTO" />
		
		
        <main_characteristics>
			<Engine>Euro 6DG Βενζίνη</Engine>
			<CO2_emissions em_unit="grCO2/km">122</CO2_emissions>
            <Fuel_consumption unit_fuel="lt/100km">5.4</Fuel_consumption>
		</main_characteristics>
		
		<economic_info_leasing>
			<monthly_leasing leasing_unit="euro" without_tax="true">239</monthly_leasing>
			<monthly_leasing leasing_unit="euro" without_tax="false" tax="24_percent">296</monthly_leasing>
			<payment_in_advance>
				<amount payment_unit="euro" without_tax="false" tax="24_percent">7.068</amount>
				<amount payment_unit="euro" without_tax="true">5.700</amount>
			</payment_in_advance>
			<retail_price retail_unit="euro">28.176</retail_price>
			<Retail_price_before_taxes retail_bef_tax_unit="euro">19.898</Retail_price_before_taxes>
			<detail_econ_info> Η τιμή ισχύει για μίσθωση 48 μηνών και καλύπτει 18.000 χλμ. τον χρόνο.</detail_econ_info>
		</economic_info_leasing>
		
		<equipment>
			<basic_equipment>
				<equip id="e25">(1) Δυναμικός Έλεγχος Ευστάθειας</equip>
				<equip id="e26">(2) Προειδοποίηση πρόσκρουσης</equip>
				<equip id="e27">(3) Εκκίνηση χωρίς χρήση κλειδιού</equip>
				<equip id="e28">(4) Σπορ δερμάτινο πολυλειτουργικό τιμόνι</equip>
				<equip id="e29">(5) Servotronic</equip>
				<equip id="e30">(6) Υποβραχιόνιο εμπρός</equip>
				<equip id="e31">(7) Έγχρωμη κεντρική οθόνη αφής 6,5’’ Visual Boost</equip>
				<equip id="e32">(8) Υπολογιστής ταξιδίου</equip>
				<equip id="e33">(9) 8 προγραμματιζόμενα πλήκτρα αφής, άμεσης πρόσβασης λειτουργιών %amp; πολύ-χειριστήριο iDrive</equip>
				<equip id="e34">(10) Ηχοσύστημα με 6 ηχεία</equip>
				<equip id="e35">(11) Σύστημα ανοικτής ακρόασης Bluetooth %amp; θύρα USB</equip>
				<equip id="e36">(12) Κλήση έκτακτης ανάγκης / Teleservices</equip>
				<equip id="e37">(13) Ηλεκτρικό χειρόφρενο</equip>
				<equip id="e38">(14) Αισθητήρας βροχής και φώτων</equip>
				<equip id="e39">(15) Πίσω φώτα LED</equip>
				<equip id="e40">(16) Ένδειξη πίεσης ελαστικών</equip>
				<equip id="e41">(17) Κιτ επισκευής ελαστικών </equip>
				<equip id="e42">(18) Επένδυση καθισμάτων με ύφασμα</equip>
				<equip id="e43">(19) Αναδιπλούμενο πίσω κάθισμα (40:20:40)</equip>
				<equip id="e44">(20) Στήριξη παιδικού καθίσματος Isofix εμπρός</equip>
				<equip id="e45">(21) Λευκά φλας</equip>
				<equip id="e46">(22) Κάθισμα συνοδηγού ρυθμιζόμενο καθ΄ ύψος</equip>
				<equip id="e47">(23) Βελούδινα ταπέτα</equip>
			</basic_equipment>
			<executive_equip>
				<exec_equip id="ex_e1">(1)Αυτόματο κιβώτιο 7 σχέσεων</exec_equip>
				<exec_equip id="ex_e2">(2)Μεταλλικό χρώμα</exec_equip>
				<exec_equip id="ex_e3">(3) Ζάντες ελαφρού κράματος 17’’</exec_equip>
				<exec_equip id="ex_e4">(4) Ράγες οροφής</exec_equip>
				<exec_equip id="ex_e5">(5) Αυτόματος διζωνικός κλιματισμός</exec_equip>
				<exec_equip id="ex_e6">(6) Αισθητήρες παρκαρίσματος πίσω</exec_equip>
				<exec_equip id="ex_e7">(7) Πακέτο φωτισμού</exec_equip>
				<exec_equip id="ex_e8">(8)Προβολείς ομίχλης LED</exec_equip>
				<exec_equip id="ex_e9">(9) Σύστημα πλοήγησης ΜΙΝΙ</exec_equip>
				<exec_equip id="ex_e10">(10) Apple CarPlay</exec_equip>
				<exec_equip id="ex_e11">(11) Χρώμα οροφής σε μαύρο, ασημί, λευκό ή στο χρώμα του αμαξώματος</exec_equip>
			</executive_equip>
		</equipment>
		
		<offer_include>
			<include>Συντήρηση και επισκευή αυτοκινήτου</include>
			<include>Πλήρη ασφαλιστική κάλυψη (ίδιες ζημιές με απαλλαγή - 24ωρη οδική βοήθεια)</include>
			<include>Τέλη κυκλοφορίας</include>
			<include>Αντικατάσταση αυτοκινήτου</include>
			<include>Δυνατότητα χρήσης προσωρινού αυτοκινήτου</include>
			<include>Αλλαγή Ελαστικών</include>
		</offer_include>



	</car>
	
	<car no="No.3">
		
		<manufacturer_brand>Toyota
			<model>Aygo Auto</model>
		</manufacturer_brand>
		
		<extra_car_info color="Κόκκινο" mini_model_description="X-Play MMT" />
			
		
        <main_characteristics>
			<Engine>Petrol / Euro 6.2</Engine>
			<CO2_emissions em_unit="grCO2/km">95</CO2_emissions>
            <Fuel_consumption unit_fuel="lt/100km">4,2</Fuel_consumption>
		</main_characteristics>
		
		<economic_info_leasing>
			<monthly_leasing leasing_unit="euro" without_tax="true">123</monthly_leasing>
			<monthly_leasing leasing_unit="euro" without_tax="false" tax="24_percent">153</monthly_leasing>
			<payment_in_advance>
				<amount payment_unit="euro" without_tax="false" tax="24_percent">2.852</amount>
				<amount payment_unit="euro" without_tax="true">2.300</amount>	
			</payment_in_advance>
			<retail_price retail_unit="euro">13.320</retail_price>
			<Retail_price_before_taxes retail_bef_tax_unit="euro">10.422,53</Retail_price_before_taxes>
			<detail_econ_info>Η τιμή ισχύει για μίσθωση 48 μηνών και καλύπτει 25.000 χλμ. τον χρόνο.</detail_econ_info>
		</economic_info_leasing>
		
		<equipment>
			<basic_equipment>
				<equip id="e48">(1) Ηλεκτρικοί εξωτερικοί καθρέπτες</equip>
				<equip id="e49">(2) Θερμαινόμενοι εξωτερικοί καθρέπτες</equip>
				<equip id="e50">(3) Χειριστήρια ηχοσυστήματος στο τιμόνι</equip>
				<equip id="e51">(4) Σύστημα ανοιχτής ακρόασης Bluetooth</equip>
				<equip id="e52">(5) Ηλεκτρικά παράθυρα εμπρός</equip>
				<equip id="e53">(6) Ραδιο/CD με 4 ηχεία και υποδοχή USB</equip>
				<equip id="e54">(7) Οθόνη συνδεσιμότητας 7"</equip>
				<equip id="e55">(8) Δυνατότητα σύνδεσης με Smartphone</equip>
				<equip id="e56">(9) Κάμερα οπισθοπορείας</equip>
				<equip id="e57">(10) Σύστημα υποβοήθησης HAC</equip>
				<equip id="e58">(11) 6 αερόσακοι</equip>
				<equip id="e59">(12) Ατσάλινες ζάντες 15'' </equip>
				<equip id="e60">(13) Βοηθητική Ρεζέρβα</equip>
				<equip id="e61">(14) Φώτα ημέρας LED</equip>
				<equip id="e62">(15) Τηλεχειρισμός κεντρικού κλειδώματος</equip>
			</basic_equipment>
		</equipment>
		
		<offer_include>
			<include>Συντήρηση και επισκευή αυτοκινήτου</include>
