=== thoTsou/XML-Projects/files/room_schema.xsd
<?xml version ="1.0" encoding ="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="hotel">
		<xs:complexType >
			<xs:sequence>
				<xs:element name="rooms" >
					<xs:complexType>	
					<xs:sequence>
						<xs:element name="room" maxOccurs="unbounded">
							<xs:complexType>	
							<xs:sequence>
								<xs:element name="roomName">
									<xs:complexType mixed="true">
										<xs:attribute name="suit" use="optional">
										<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="yes" />
													<xs:enumeration value="no" />
												</xs:restriction>
											</xs:simpleType>
										</xs:attribute>
										<xs:attribute name="wiFi" default="yes" use="optional">
										<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="yes" />
													<xs:enumeration value="no" />
												</xs:restriction>
											</xs:simpleType>
										</xs:attribute>
										<xs:attribute name="floor" type="xs:string"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="capacity">
									<xs:complexType>
										<xs:sequence>
										<xs:element name="cap" >
											<xs:complexType>
											<xs:attribute name="capNumber" use="required">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:enumeration value="1" />
														<xs:enumeration value="2" />
														<xs:enumeration value="3" />
														<xs:enumeration value="4" />
													</xs:restriction>
												</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="beds" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="single" type="xs:string" minOccurs="0" maxOccurs="1"/>
											<xs:element name="double" type="xs:string" minOccurs="0" maxOccurs="1"/>
											<xs:element name="XL" type="xs:string" minOccurs="0" maxOccurs="1"/>
											<xs:element name="bedCouch" type="xs:string" minOccurs="0" maxOccurs="1"/>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="views" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="view" type="xs:string" maxOccurs="unbounded"/>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="amenities" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence>	
											<xs:element name="amenity" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType mixed="true">
													<xs:attribute name="extraCharge" type="xs:string" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="pricePerSeason" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence>	
											<xs:element name="price" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType mixed="true">
													<xs:attribute name="season" use="required" >
													<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:enumeration value="low" />
														<xs:enumeration value="med" />
														<xs:enumeration value="high" />
													</xs:restriction>
													</xs:simpleType>
													</xs:attribute>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="code" type="xs:ID" use="required"/>
							</xs:complexType>
						</xs:element>
						
					
						
					</xs:sequence>
					</xs:complexType>
					
				</xs:element>
				
				<xs:element name="offers">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="offer" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
								<xs:sequence>
									<xs:element name="date" >
										<xs:complexType>
											<xs:attribute name="startFrom" type="xs:string" use="required" />
											<xs:attribute name="endAt" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="offerRooms" type="xs:IDREFS" use="required" />
								<xs:attribute name="offerPrice" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
					
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="stars" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	
	
</xs:schema>

=== thoTsou/XML-Projects/files/Question1.xml
<?xml version ="1.0" encoding ="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="room_present1.xsl" ?>



<hotel name="FILOXENIA" stars="4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="room_schema.xsd">
	<rooms>
		<room code="No.1">
			<roomName suit="yes" floor="5">Red Room</roomName>
			<capacity>
				<cap capNumber="4" />
			</capacity>
			<beds>
			    <double>1</double>
				<XL>1</XL>
			</beds>
			<views>
				<view>Sea</view>
				<view>Street view</view>
			</views>
			<amenities>
				<amenity>amenity 1</amenity>
				<amenity extraCharge="30 euro">amenity 2</amenity>
				<amenity>amenity 3</amenity>
				<amenity>amenity 4</amenity>
			</amenities>
			<pricePerSeason>
				<price season="low">300 euro per night</price>
				<price season="med">600 euro per night</price>
				<price season="high">800 euro per night</price>
			</pricePerSeason>
		</room>
		
		
		<room code="No.2">
			<roomName floor="2">Green Room</roomName>
			<capacity>
				<cap capNumber="2" />
			</capacity>
			<beds>
			    <double>1</double>
			</beds>
			<views>
				<view>Street view</view>
			</views>
			<amenities>
				<amenity>amenity 1</amenity>
			</amenities>
			<pricePerSeason>
				<price season="low">25 euro per night</price>
				<price season="med">40 euro per night</price>
				<price season="high">55 euro per night</price>
			</pricePerSeason>
		</room>
		
		<room code="No.3">
		
			<roomName floor="1" wiFi="no">Yellow Room</roomName>
			<capacity>
				<cap capNumber="1" />
			</capacity>
			<beds>
			    <single>1</single>
			</beds>
			<views>
				<view>Mountain View</view>
			</views>
			<amenities>
				<amenity>amenity 1</amenity>
				<amenity extraCharge="5 euro">amenity 2</amenity>
			</amenities>
			<pricePerSeason>
				<price season="low">20 euro per night</price>
				<price season="med">40 euro per night</price>
				<price season="high">50 euro per night</price>
			</pricePerSeason>

		</room>
		
	</rooms>


	<offers>
		<offer offerRooms="No.1" offerPrice="150 euro">
			<date startFrom="October 10" endAt="16 October" />
		</offer>
		<offer offerRooms="No.2 No.3" offerPrice="20 euro">
			<date startFrom="October 10" endAt="16 October" />
		</offer>
	</offers>


</hotel>
